# Build stage
FROM maven:3.8.6-eclipse-temurin-17 AS build
WORKDIR /app
# Copy the pom.xml file
COPY noteapp/backend/pom.xml .
# Download dependencies
RUN mvn dependency:go-offline
# Copy the source code
COPY noteapp/backend/src ./src
# Build the application
RUN mvn package -DskipTests

# Run stage
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
